name: Docker Image CI

on:
  push:
    branches: [ "personal" ]
  pull_request:
    branches: [ "personal" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v3.1.0
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2

    - name: Log in to the Github Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: github.repository == 'theMaster23/mastodon' && github.event_name != 'pull_request'

    - name: Extract metadata
      uses: docker/metadata-action@v4
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        flavor: latest=auto
        tags: |
          type=edge,branch=main
          type=pep440,pattern={{raw}}
          type=pep440,pattern=v{{major}}.{{minor}}
          type=ref,event=pr

    - uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        provenance: false
        builder: ${{ steps.buildx.outputs.name }}
        push: ${{ github.repository == 'theMaster23/mastodon' && github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
